Post/urls.py
from django.urls import path
from .views import CreatePost,DeletePost,UpdatePost,PostList,PostDetail
app_name='Post'



urlpatterns = [
    path('create/',CreatePost.as_view(),name='create'),
    path('delete/<int:pk>',DeletePost.as_view(),name='delete'),
    path('update/<int:pk>',UpdatePost.as_view(),name='update'),
    path('list/',PostList.as_view(),name='list'),
    path('detail/<int:pk>',PostDetail.as_view(),name='detail'),
  


]

myapp/urls.py
from django.urls import path
from .views import Homepage,LoginPage,SignUp,ProfilePage
from django.contrib.auth.views import LogoutView


app_name='myapp'



urlpatterns = [
    path('',Homepage.as_view(),name='index'),
    path('login/',LoginPage.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page='/'),name='logout'),
    path('signup/',SignUp.as_view(),name='signup'),
    path('profile/',ProfilePage.as_view(),name='profile'),


]

todoList/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Post import urls 
from myapp import urls  
from django.contrib.auth import views as auth_views
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('myapp.urls', 'myapp'), namespace='myapp')),
    path('post/', include(('Post.urls', 'Post'), namespace='Post')),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="passwordview.html",html_email_template_name='passwordemail.html'),name='password_reset'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name="passworddone.html"),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="passwordconfirm.html"),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name="passwordcomplete.html"),name='password_reset_complete'),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Post/models.py
from django.db import models
from django.contrib.auth.models import User 


class MyPost(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField(max_length=300,blank=True,null=True)
    image=models.ImageField(blank=True,null=True,upload_to="images/")
    time=models.DateTimeField(blank=True,null=True)
    user=models.ForeignKey(User,models.CASCADE)
    checked=models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering=['checked']

myapp/models.py
from django.db import models

from django.contrib.auth.models import User


class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to='avatars/',default='6596121.png')

    def __str__(self):
        return self.user.username
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
    

myapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile

class SignUpForm(UserCreationForm):

    email=forms.EmailField(max_length=300)

    class Meta:
        model=User
        fields=('username','email','password1','password2',)
        



class UserUpdate(forms.ModelForm):
    class Meta:
        model=User
        fields=['email','username']


class UpdateProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['avatar']

Post/views.py
from django.views.generic import DeleteView,CreateView,UpdateView,ListView,DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.contrib import messages

from .models import MyPost
from django.shortcuts import render


class PostList(LoginRequiredMixin,ListView):
    model=MyPost
    context_object_name='posts'
    template_name = 'Post/postList.html'


    def get_queryset(self):
       return MyPost.objects.filter(user=self.request.user).order_by('-id')
    

class PostDetail(LoginRequiredMixin,DetailView):
    http_method_names=["get"]
    model=MyPost
    context_object_name='posts'
    template_name="Post/detail.html"

    def get_queryset(self):

        myQuery= super().get_queryset()
        return myQuery.filter(user=self.request.user)






class UpdatePost(LoginRequiredMixin,UpdateView):
    model=MyPost
    success_url=reverse_lazy('Post:list')
    fields=['title','description','image','time','checked']
    context_object_name = 'post'
    template_name="Post/edit.html" 


    def form_valid(self, form):
        messages.success(self.request,"The post was successfully updated")
        return super().form_valid(form)
    
    def get_queryset(self):

        myQuery= super().get_queryset()
        return myQuery.filter(user=self.request.user)


class CreatePost(LoginRequiredMixin,CreateView):
    model=MyPost
    fields=['title','description','image','time','checked']
    template_name="Post/postForm.html" 
    success_url=reverse_lazy('Post:list')
    

    def dispatch(self, request, *args, **kwargs):
        self.request=request
        return super().dispatch(request, *args, **kwargs)
    def form_valid(self, form):
        obj=form.save(commit=False)
        obj.user=self.request.user
        obj.save()
       
        
        return super().form_valid(form)
    
    def post(self,request,*args,**kwargs):
        from datetime import datetime
        checked_str = request.POST.get("checked")
        checked = True if checked_str in ["on", "1", "true"] else False
        time_str = request.POST.get("time", "").strip()
        time = None
        if time_str:
            time = datetime.strptime(time_str, "%Y-%m-%dT%H:%M")
        post=MyPost.objects.create(
            title=request.POST.get('title'),
            description=request.POST.get('description'),
            image=request.FILES.get('image'),
            time=time,
            user=request.user,
            checked=checked,
        )
        return render(request, "Post/postList.html", {"posts": [post]},content_type="text/html",)



class DeletePost(LoginRequiredMixin,DeleteView):
    model=MyPost
    context_object_name='posts'
    success_url=reverse_lazy('Post:list')
    template_name="Post/delete.html"

    def form_valid(self, form):
        messages.success(self.request,"the Post deleted successfully")
        return super().form_valid(form)
    
    def get_queryset(self):
        myQuery=super().get_queryset()
        return myQuery.filter(user=self.request.user)
    

myapp/views.py
from django.views.generic import TemplateView,FormView,View
from django.contrib.auth.views import LoginView
from django.contrib import messages
from .forms import SignUpForm,UpdateProfile,UserUpdate
from django.contrib.auth import login
from django.shortcuts import render,redirect

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Profile







class Homepage(TemplateView):

    template_name="home.html"



class SignUp(FormView):
    template_name="signup.html"
    form_class=SignUpForm
    redirect_authenticated_user=True
    success_url = reverse_lazy('myapp:login')

    def form_valid(self, form):
        user=form.save()
        if user:
            login(self.request,user)
        return super(SignUp,self).form_valid(form)
    
    
    


  
class LoginPage(LoginView):
    template_name="login.html"
    redirect_authenticated_user=True

    def get_success_url(self):
        
        return "/"
    


    def form_invalid(self, form):
        messages.error(self.request,'Invalid username or password')
        return render(self.request,self.template_name,{"form":form})
        
        
    

class ProfilePage(LoginRequiredMixin,View):
    def get(self,request):
        userForm=UserUpdate(instance=request.user)
        profileForm=UpdateProfile(instance=request.user.profile)

        context={
            "userForm":userForm,
            "profileForm":profileForm,

        }

        return render(request,'profile.html',context)
    
    def post(self,request):
        userForm=UserUpdate(request.POST,instance=request.user)
        profileForm=UpdateProfile(request.POST,request.FILES,instance=request.user.profile)

        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            profileForm.save()
            messages.success(request,'Your profile has been changed successfully')
            return redirect('myapp:profile')
        else:
            context={
                    'userForm':userForm,
                    'profileForm':profileForm,
            }
            messages.error(request,'error cant update your profile')
            return render(request,'profile.html',context)

Post/templates/Post/delete.html
{%extends 'base.html'%}

{%block title%}Delete Page{%endblock%}


{%block content%}
<div class="da relative flex min-h-screen flex-col justify-center overflow-hidden bg-gray-50">
  <div class="absolute inset-0 bg-center "></div>

  <div class="group relative m-0 flex h-[400px] w-[900px] rounded-xl shadow-xl ring-gray-900/5 sm:mx-auto sm:max-w-lg">
    <!-- Image -->
    <div class="z-10 h-full w-full overflow-hidden rounded-xl border border-gray-200 opacity-80 transition duration-300 ease-in-out group-hover:opacity-100 dark:border-gray-700 dark:opacity-70">
      <img src="https://i.redd.it/ldc03vxccuqe1.jpeg"
           class="block h-full w-full object-cover object-center transition duration-300 group-hover:scale-110" alt="" />
    </div>

    <!-- Content-->
    <div class="absolute bottom-0 z-20 w-full bg-black/40 p-4 rounded-b-xl">
      <h1 class="font-serif text-xl font-bold text-white">Delete Task {{ posts.id }}</h1>
      <p class="text-sm text-gray-200 mb-3">Are you sure you want to delete this task card ({{posts.title}})?</p>

      <form method="POST">
        {% csrf_token %}
        <div class="flex gap-2">
          <input type="submit" value="Delete" class="px-3 py-1 rounded bg-red-600 text-white hover:bg-red-700 cursor-pointer">
          <a href="{% url 'Post:list' %}" class="px-3 py-1 rounded border border-gray-300 text-gray-100 hover:bg-gray-200 hover:text-black">
            Cancel
          </a>
        </div>
      </form>
    </div>
  </div>
</div>


{%endblock%}

Post/templates/Post/postList.html
{%extends 'base.html'%}



{%block title%}List Page{%endblock%}




{%block content%}



    <!-- component -->
    <div class="my-10 mx-10 max-w-lg mx-auto my-10  p-8 rounded-xl bg-green-100  shadow shadow-slate-300" >
        <div class="flex flex-row justify-between items-center">
            <div>
                <h1 class="text-3xl font-medium">Tasks list</h1>
            </div>
            
        </div>
        <p class="text-slate-500">Hello, here are your latest tasks</p>
        {%if posts%}
{%for post in posts%}
        <div class="tasks" class="my-5">
            <div id="task-{{post.id}}" class="flex justify-between items-center border-b border-slate-200 py-3 px-2 border-l-4  border-l-transparent">
                <div class="inline-flex items-center space-x-2">
                    <div>
                        {%if post.checked%}
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-slate-500">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                          </svg>     
                          {%else%}
                           <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                         </svg>
                        {%endif%}
                    </div>
                    <div class="ml-2 px-2 py-1 rounded text-sm 
                                {% if post.checked %}bg-green-100 text-green-800{% else %}bg-red-100 text-red-800{% endif %}"  >{{post.title}}</div>
                </div>
                <div class="flex items-center  gap-2">
                    <a class="text-white bg-gradient-to-r from-pink-400 via-pink-500 to-pink-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-pink-300 dark:focus:ring-pink-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2" href="{%url 'Post:detail' post.id%}">detail</a>
                    <a href="{%url 'Post:update' post.id%}"> 
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                    width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.5"
                    stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" role="img"
                    class="inline-block">
                    <path d="M3 21v-3.75L17.81 2.44a1 1 0 0 1 1.41 0l1.34 1.34a1 1 0 0 1 0 1.41L6.75 20.99 3 21z"/>
                    <path d="M14.75 6.25l3 3"/>
                    </svg>
                    </a>       
                    <a href="{%url 'Post:delete' post.id %}">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 text-slate-500 hover:text-slate-700 hover:cursor-pointer">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                      </svg>    
                    </a> 
                             
                </div>
            </div>
          
    </div>
    {%endfor%}
    {%endif%}

{%endblock%}

myapp/templates/home.html
{% extends "base.html" %}
{%load static%}


{%block title%}Home Page{%endblock%}

{%block content%}

<h1 class="text-5xl mt-24 mx-24 mb-2">
  Welcome to our site
</h1>

<p class="font-sans text-xl mx-24 mt-2">
  In here you can make your Tasks
</p>

<div class="flex">
  <p class="text-xl mr-3 ml-24 mt-2">
    Start your
  </p>
  <a href="{% url 'myapp:signup' %}"
     class="text-xl mt-2 text-gray-900 bg-gradient-to-r from-red-200 via-red-300 to-yellow-200 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-red-100 dark:focus:ring-red-400 font-medium rounded-lg text-sm px-5 py-2.5 text-center mb-2">
    journey
  </a>
</div>

<div class="relative">
  <!-- On mobile: static (normal flow, below text) -->
  <!-- On desktop: absolute, floating on top-right -->
  <div class="mt-6 flex justify-center
            md:absolute md:-top-12 md:right-60 md:mt-0">
    <div class="w-60 h-60 md:w-80 md:h-80 rounded-full bg-blue-400 flex justify-center items-center">
      <img src="{% static 'gif/mysun.gif' %}" alt="Sun Animation" class="w-40 md:w-60 h-auto" />
    </div>
  </div>
</div>

{%endblock%}

myapp/templates/passwordcomplete.html
{%extends "base.html"%}

{%block title%}success page{%endblock%}


{%block content%}

<div >
        <p style="margin:208px 467px">Your password has been reset successfully. you can now go on <a  style="color:green;"  href="{%url 'myapp:login'%}">Login</a></p>
</div>

{%endblock%}

myapp/templates/passwordemail.html
<h1>Hello my friend</h1>

<p>Right now you are getting this  message becuase you want to reset you password for your user account  at {{domain}}</p>


<p> please click on the following link for changing the password:</p>


{{protocol}}://{{domain}}{%url 'password_reset_confirm' uidb64=uid token=token%}

myapp/templates/passwordview.html
{%extends 'base.html'%}



{%block title%}password change{%endblock%}





{%block content%}
<style>
#id_email{
	border:1px blue solid;
	background-color:white;
}


</style>






<div class="mt-20 mx-auto max-w-sm p-6 bg-gray-300 border border-gray-400 rounded-lg shadow-sm dark:bg-gray-400 dark:border-gray-700">
    
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Reset Password</h5>
    <form method="post" class="card"  >
		{% csrf_token %}
	    <h2 class="text-center"></h2>
		{% for f in form %}
	    		{{ f.label_tag }} 
	        	{{ f }}
	        	{% if f.errors %}
	        		<small>{{ f.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons  mt-3">
			<input   type="submit" value="Send" class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-green-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-blue-800">
			        			<a href="{%url 'myapp:login' %}"  class=" inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800e">Cancel</a>

		</div>

	</form>
    
</div>

{%endblock%}

myapp/templates/signup.html
{%extends "base.html"%}


{%block title%}Signup{%endblock%}



{%block content%}



<style>

#id_username{

 border:1px solid white;
 border-radius:10px;
 margin-right:10px;
 
}
#id_username:focus{
   border:1px solid blue;

}
#id_email{

 border:1px solid white;
 border-radius:10px;
 margin-right:10px;
 
}
#id_email:focus{
   border:1px solid blue;

}

#id_password1{

 border:1px solid white;
 border-radius:10px;
 margin-right:10px;
 
}
#id_password1:focus{
   border:1px solid blue;

}

#id_password2{

 border:1px solid white;
 border-radius:10px;
 margin-right:10px;
 
}
#id_password2:focus{
   border:1px solid blue;

}


</style>




<div  class="max-w-6xl mx-auto justify-center items-center my-30">
                <div class="w-full px-8 md:px-32 lg:px-24" >
                  <form action="{%url 'myapp:signup'%}"  method="POST"  class="  bg-white rounded-md shadow-2xl p-5" id="formSignin" novalidate>
                    {% csrf_token %}
                    <h1 class="text-gray-800 font-bold text-2xl mb-1">Sign Up!</h1>
                    <p class="text-sm font-normal text-gray-600 mb-8">Please fill the form<span id="name"></span></p>
                  
                    <div class="alert"></div>
                     <h1>Username:</h1>
                    <div class="flex items-center border-2 mb-8 py-2 px-3 rounded-2xl">
                       
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5.121 17.804A9 9 0 0112 15a9 9 0 016.879 2.804M12 12a4 4 0 100-8 4 4 0 000 8z" />
                    </svg>
                     {{form.username}}
                    </div>
                    {%if form.username.errors%}
                    <small class="text-red-500">{{form.username.errors|striptags}}</small>
                    {%endif%}
                    <h1>Email:</h1>
                    <div class="flex items-center border-2 mb-12 py-2 px-3 rounded-2xl">
                     <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="h-5 w-5 text-gray-400"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M16 12a4 4 0 10-8 0 4 4 0 008 0zm0 0v1.5a2.5 2.5 0 005 0V12a9 9 0 10-9 9m4.5-1.206a8.959 8.959 0 01-4.5 1.207"
                        />
                      </svg>
                     {{form.email}}
                    </div>
                    {%if form.email.errors%}
                    <small class="text-red-500">{{form.email.errors|striptags}}</small>
                    {%endif%}
                    <h1>Password:</h1>
                     <div class="flex items-center border-2 mb-12 py-2 px-3 rounded-2xl">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="h-5 w-5 text-gray-400"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fillRule="evenodd"
                          d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                          clipRule="evenodd"
                        />
                      </svg>
                     {{form.password1}}
                    </div>
                    {%if form.password1.errors%}
                    <small class="text-red-500">{{form.password1.errors|striptags}}</small>
                    {%endif%}
                    <h1>Confirm Password:</h1>
                     <div class="flex items-center border-2 mb-12 py-2 px-3 rounded-2xl">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="h-5 w-5 text-gray-400"
                        viewBox="0 0 20 20"
                        fill="currentColor"
                      >
                        <path
                          fillRule="evenodd"
                          d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                          clipRule="evenodd"
                        />
                      </svg>
                     {{form.password2}}
                 
                    </div>
                    {%if form.password2.errors%}
                    <small class="text-red-500">{{form.password2.errors|striptags}}</small>
                    {%endif%}
                    <button
                      type="submit"
                      class="block w-full bg-green-600 mt-5 py-2 rounded-2xl hover:bg-green-700 hover:-translate-y-1 transition-all duration-500 text-white font-semibold mb-2"
                    >
                      signup
                    </button>
                   
                    <div class="flex justify-between mt-4">
                      <a
                        href="{%url 'myapp:login' %}"
                        class="text-sm ml-2 hover:text-blue-500 cursor-pointer hover:-translate-y-1 duration-500 transition-all"
                        >Do you have an account?</a
                      >
                    </div>
                  </form>
                </div>
              </div>










{%endblock%}

templates/base.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
<nav class="w-full flex flex-wrap items-center justify-between p-3 bg-teal-200/20">
   <a href="/"><i class='bx bx-sun' style="font-size: 40px; color: orange;"></i><h1 class="mx-4 font-bold text-teal-900 hover:text-teal-500" style="font-size:40px;display:inline-block;">ToDO-List</h1></a>
   <a></a>
    <div class="flex md:hidden">
        <button id="hamburger">
          <img class="toggle block" src="https://img.icons8.com/fluent-systems-regular/2x/menu-squared-2.png" width="48" height="48" />
          <img class="toggle hidden" src="https://img.icons8.com/fluent-systems-regular/2x/close-window.png" width="48" height="48" />
        </button>
    </div>
    <div
        class="toggle hidden w-full md:w-auto md:flex text-right text-bold mt-5 md:mt-0 border-t-2 border-teal-900 md:border-none">
         <a href="/"
            class="block md:inline-block text-teal-900 hover:text-teal-500 px-3 py-3 border-b-2 border-teal-900 md:border-none ">Home
        </a>
        {%if user.is_authenticated%}
        
        <a href="{%url 'Post:list'%}"
            class="block md:inline-block text-teal-900 hover:text-teal-500 px-3 py-3 border-b-2 border-teal-900 md:border-none">myList
        </a>
        <a href="{%url 'Post:create'%}"
            class="block md:inline-block text-teal-900 hover:text-teal-500 px-3 py-3 border-b-2 border-teal-900 md:border-none js-todo">addTOdo
        </a>
        <a href="{%url 'myapp:profile'%}"
            class="block md:inline-block text-teal-900 hover:text-teal-500 px-3 py-3 border-b-2 border-teal-900 md:border-none">Profile
        </a>
        <p class="block md:inline-block text-yellow-900 hover:text-yellow-500 px-3 py-3 border-b-2 border-teal-900 md:border-none">welcome {{user.username}}</p>
       <form method="post" action="{% url 'myapp:logout' %}" class="inline">
            {% csrf_token %}
            <button type="submit" class="block md:inline-block text-teal-900 hover:text-teal-500 px-3 py-3 border-b-2 border-teal-900 md:border-none">
                Logout
            </button>
        </form>
        {%else%}
       
    </div>
    <a href="{%url 'myapp:login'%}"
        class="toggle hidden md:flex w-full md:w-auto px-4 py-2 text-right bg-teal-900 hover:bg-teal-500 text-white md:rounded">LogIn
        
    </a>
    {%endif%}
</nav>








{%block content%}{%endblock%}




<!-- component -->
<div class="fixed inset-0 bg-gray-800/50 flex items-center justify-center z-50 hidden js-card">
  <div class="  max-w-2xl  h-[670px]    w-full bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-all">
    <svg class="ml-auto fill-current text-red-700 w-6 h-6 cursor-pointer js-todo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"/>
        </svg>
    


    <div class=" p-5 space-y-4">
      <div>
        <h3 class="text-xl font-bold text-gray-900">Title:</h3>
        <input  data-post-url="{%url 'Post:create'%}"   type="text" class="border-2 border-blue-500 my-4 w-full js-post-title"placeholder="Enter your title" maxlength="100" />

      </div>
      <div>
        <h3 class="text-xl font-bold text-gray-900">description:</h3>
        <textarea  data-post-url="{%url 'Post:create'%}"    class="border-2 border-blue-500 my-4 w-full js-post-description"placeholder="Enter your things"row="3" maxlength="230" ></textarea>

        
      </div>
      
      <div class="justify-between items-center">
        <div class="space-y-1">
          <div style="display:inline-block" class=" my-3 text-xl font-bold text-gray-900">Time:</div>
            <input data-post-url="{%url 'Post:create'%}"   type="datetime-local"  class="border-2 border-blue-500 my-4 w-full js-post-time" maxlength="100"  />

        </div>
          <div class="justify-between items-center">
        <div class="space-y-1">
          <div style="display:inline-block" class=" my-3 text-xl font-bold text-gray-900">image:</div>
            <input data-post-url="{%url 'Post:create'%}"  type="file"   class="border-2 border-blue-500 my-4 w-full js-post-image"  />

        </div>

        <div class="justify-between items-center">
        <div class="space-y-1">
          <div style="display:inline-block"  class=" my-3 text-xl font-bold text-gray-900">Checked:</div>
            <input type="checkbox"  class=" border-2 border-blue-500 my-4  js-post-checked"        data-post-url="{%url 'Post:create'%}" />

        </div>
        
        

      <button class=" w-full my-10 px-6 bg-pink-600 hover:bg-pink-700 text-white font-medium py-3 rounded-lg transition-colors js-button" >
       Submit
      </button>
 
    </div>
  </div>
</div>








<script>
    document.getElementById("hamburger").onclick = function toggleMenu() {
        const navToggle = document.getElementsByClassName("toggle");
        for (let i = 0; i < navToggle.length; i++) {
          navToggle.item(i).classList.toggle("hidden");
        }
      };
</script>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="{%static 'js/main.js'%}"></script>
</body>
</html>